name: Continuous integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build apps and packages
        run: yarn build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run test on apps and packages
        run: yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run lint on apps and packages
        run: yarn lint
